services:
  audiostudio:
    build: .
    container_name: audiostudio
    restart: always
    ports:
      - "127.0.0.1:3005:3000"
    environment:
      - MAX_DEMUCS_JOBS=${MAX_DEMUCS_JOBS:-1}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-20}
      - MAX_JOBS_PER_IP=${MAX_JOBS_PER_IP:-1}
